### ISSUE TITLE
Add example usage of the scaffolder in readme 

### ISSUE THREAD

**Issue by trevtrich** [travi/project-scaffolder#259]
When I went to add a language scaffolder to the project, it wasn't clear to me whether I was able to pass in a key like `javascript` and it would add that language in for me, or if this was just my point to inject language scaffolders on my own. From other examples i'm seeing that it is the latter, but it could be helpful to have that be made obvious with an example.

**Comment by travi** [comment]
i agree that a usage example would be helpful, for many reasons. when we do add it, i would like to follow the remark approach similar to [how it is done for the js scaffolder](https://github.com/travi/javascript-scaffolder/blob/e386332e19e319652efc276c926abe21ac8f4a42/.remarkrc.js#L13)

specifically for adding the language scaffolders, i'm also open to feedback for making the [options definition](https://github.com/travi/project-scaffolder#options) more clear (it could also be out of date)

**Comment by trevtrich** [comment]
closed with #263
