### ISSUE TITLE
readme sometimes does not include the consumer badge zone

### ISSUE THREAD

**Issue by travi** [travi/project-scaffolder#475]
even though the mustache template [includes it unconditionally](https://github.com/travi/project-scaffolder/blob/221810fbda00e8e3cb33668f310ebd914d46ccb1/templates/README.mustache#L18-L19)

it seems to be missing in cases where the ["Usage" heading](https://github.com/travi/project-scaffolder/blob/221810fbda00e8e3cb33668f310ebd914d46ccb1/templates/README.mustache#L14-L17) and [content](https://github.com/travi/project-scaffolder/blob/221810fbda00e8e3cb33668f310ebd914d46ccb1/templates/README.mustache#L20-L23) are not included, like when generating a js application or docs-only repo.

the impact is that reference definitions are added for consumer badges, like the license, but nothing actually uses them. this then fails remark-lint because of the unused definition.

it is possible, although i havent confirmed, that the badge zone is getting included in the readme generation (which appears to be true, both by the template logic, but also by the unit tests) and then later stripped. the most likely place they could be getting stripped is in the `npm run generate:md` that is run after successful scaffolding. this would make it hard to reproduce in a test since that step is outside the scope of what is currently tested.

**Comment by travi** [comment]
some details from a private repo that i just scaffolded that might help eliminate some possible failure scenarios.
* project was unlicensed, so no license badge was included. since there were no unused definitions, the lint check did not fail, but the zone is still missing
* since the project was private, there are also no status badges. this means that the status zone is empty, but it _does_ exist. i was thinking that the empty zone was maybe getting stripped out as some sort of optimization, but this suggests that isnt the case

**Comment by travi** [comment]
I'm willing to bet the problem is actually somewhere in https://www.github.com/form8ion/remark-inject-badges/tree/master/src%2Fzone-mutator.js

**Comment by trevtrich** [comment]
So it appears that [this is a feature of the TOC plugin](https://github.com/remarkjs/remark-toc/issues/18). When we don't have a Usage header, the consumer badge zone falls within the TOC and thus gets eaten by it 👎 . How would you feel about moving the license up above the TOC?

**Comment by trevtrich** [comment]
Scratch ☝️  comment. Realizing not just licenses that could target the consumer badges. 😏 let me know if you have any strong thoughts here.

**Comment by travi** [comment]
ah, good find. i had started to catch on to the fact that it was more related to the missing header than the other things i thought were likely, initially. i hadn't considered the TOC yet tho.

> How would you feel about moving the license up above the TOC?

so, interestingly, i've been manually moving/re-adding the consumer zone to just after the status zone when this happens. i could see the logic being valuable enough to be included to place it in different locations based on whether the header should be included or not.

**Comment by travi** [comment]
as a side note, i have some thoughts that i havent found time for yet around making the contents of the readme more dynamic with additional remark plugins. i've been wanting to add content to more of the sub-scaffolders/plugins for the usage section, but would need more dynamic inclusion capability for it to work. 

i don't think it really matters too much for this fix, but figured it could be worthwhile context at least. the main detail that seems important is that my goal is to move toward the mustache template that builds the very initial content to be more minimal than it even is now, with the goal that the more dynamic details are handled with the remark plugins.
